### ISSUE TITLE
Using Alt+L to leave world prevents loading of other worlds - requires page refresh

### ISSUE THREAD

**Issue by turt2live** [matrix-org/thirdroom#325] opened 2022-09-23 01:34 UTC
1. Enter a world
2. <kbd>Alt</kbd>+<kbd>L</kbd>
3. Try to load world again (button does nothing)
4. Refresh page
5. Enter a world just fine

**Comment by NateTheGreatt** [comment] 2022-09-23 19:09
👍 confirmed, dupe of https://github.com/matrix-org/thirdroom/issues/291

**Closed by NateTheGreatt** 2022-09-23 19:09 UTC
