### ISSUE TITLE
editor

### ISSUE THREAD

**Issue by montage125** [matrix-org/thirdroom#400] opened 2022-10-17 02:57 UTC
Is there an editor?
1. I hope you can use the editor to create models, import models, upload pictures/videos/files and other content.
2. One click publishing, like hubs, can be released quickly.

**Comment by robertlong** [comment] 2022-10-17 17:33
Right now there's the Third Room Unity Exporter which we're using internally for the Terra and UK City scenes:

https://github.com/matrix-org/thirdroom-unity-exporter

It's really great especially if you're familiar with Unity or you have existing Unity content that you want to port to Third Room. However, we'll be working on the integrated editor again next year.

Closing as a duplicate of #62

**Closed by robertlong** 2022-10-17 17:33 UTC
